import json
import os
import argparse
import shutil
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Add depth file paths to transforms.json for POGS training.")
    parser.add_argument("--transforms", type=str, required=True, help="Path to transforms.json generated by ns-process-data.")
    parser.add_argument("--depth_dir", type=str, required=True, help="Path to the directory containing .npy depth files (from realsense_capture.py).")
    args = parser.parse_args()

    transforms_path = Path(args.transforms)
    base_dir = transforms_path.parent
    depth_src_dir = Path(args.depth_dir)
    
    # Create a depth directory in the processed folder
    depth_dest_dir = base_dir / "depth"
    depth_dest_dir.mkdir(exist_ok=True)
    
    print(f"Processing {transforms_path}...")
    
    with open(transforms_path, 'r') as f:
        data = json.load(f)
    
    frames = data.get("frames", [])
    matched = 0
    
    for frame in frames:
        # frame['file_path'] looks like "images/frame_00001.png"
        img_path = Path(frame['file_path'])
        fname = img_path.stem # frame_00001
        
        # Look for corresponding npy file
        depth_fname = f"{fname}.npy"
        src_depth_path = depth_src_dir / depth_fname
        
        if src_depth_path.exists():
            # Copy to processed folder
            dest_depth_path = depth_dest_dir / depth_fname
            shutil.copy2(src_depth_path, dest_depth_path)
            
            # Update json with relative path
            # POGS dataloader expects depth_file_path relative to transforms.json location usually
            frame['depth_file_path'] = f"depth/{depth_fname}"
            matched += 1
        else:
            print(f"Warning: Depth file not found for {fname} at {src_depth_path}")

    # Save updated json
    with open(transforms_path, 'w') as f:
        json.dump(data, f, indent=4) # Use 4 spaces for readability

    print(f"Updated {matched}/{len(frames)} frames with depth paths.")
    print("You can now run ns-train pogs!")

if __name__ == "__main__":
    main()
