# @package _global_
defaults:
  - override /data: rlbench_act_pcd_dataset
  - override /model: rlbench_act_pcd_model

task_name: pretrained_pointnet2_pcd

data:
  batch_size_train: 8

trainer:
  accumulate_grad_batches: 4

model:
  policy:
    backbone:
      _target_: src.models.components.pcd_encoder.pointnet2.PointNet2
      in_channels: 70  # 6 (xyz+rgb) + 64 (DINO)
      num_classes: 0
      pretrained_path: checkpoints/pointnet2_ssg_modelnet40.pth
